[server]
headless = true
port = 8501
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#183232"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
# #D1FF71 anemolabs light green
