[server]
headless = true
port = 8501
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#004D43"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"